### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by victornewman** [lsyk4/Bubble-Chat-Animation#2]
Is it possible to add avatars on chat animation?

**Comment by lsyk4** [comment]
Hi! 
At moment it hasn't avatars, but give me a few days and you can download a new copy of the repository updated. I will comment this issue to notify you if you are interested yet.
Greetings!

**Comment by lsyk4** [comment]
Sorry for the delay @victornewman !
Now is possible to use avatars. I updated the repository a moments ago, then you can download a new copy of it.
Greetings!
